service: chat

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: us-east-1

  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-connections
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hisocket:
    handler: handler.connect
    events:
      - websocket: $connect
  byesocket:
    handler: handler.disconnect
    events:
      - websocket: $disconnect
  speaksocket:
    handler: handler.msock
    events:
      - websocket: $default

resources:
  Resources:
    ConnectionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
